<a href="https://colab.research.google.com/github/samuelj1323/ML_Learning/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00.Pytorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/
If you have any questions: go to the course github


In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu118


## Intro to Tensors

### Creating a tensor



In [2]:
#Scalar

scalar = torch.tensor(7)
scalar

tensor(7)

Torch tensor: https://pytorch.org/docs/stable/tensors.html
.

In [3]:
scalar.ndim

0

In [4]:
#get tensor back as python int
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7,7])
#Typically has more than one number

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix

MATRIX = torch.tensor([[7,8],
[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[0]

tensor([7, 8])

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

###Random Tensors

Why random tensors?
Random tensors are important because the way taht many NN learn is that htey start with tensors ful of rnadom numbers and hten adjust those random numbers to better represent the data.

`Start with Random number -> look at data => update random numbers => look at data => update the random numbers `

In [16]:
#Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9410, 0.4532, 0.7100, 0.2806],
        [0.5374, 0.5511, 0.1278, 0.2104],
        [0.7916, 0.9716, 0.6462, 0.1705]])

In [17]:
random_tensor.ndim

2

In [18]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [19]:
torch.rand(2,3,2)

tensor([[[0.6563, 0.0557],
         [0.9821, 0.6277],
         [0.8516, 0.7063]],

        [[0.8510, 0.0618],
         [0.2445, 0.5533],
         [0.8382, 0.3968]]])

### Zeros and ones


In [20]:
# Create a tensor of all zeros
zero = torch.zeros(3,4)
zero * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [23]:
# Use torch.arange()
one_to_ten = torch.arange(start=0,end=10, step=1)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
# Creating tensors like (same shape)
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype=None, device=None, requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [27]:
float_32_tensor.dtype

torch.float32

### Tensor datatype is one of the 3 big errors you run into with pytorch and deep learning

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [29]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [30]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])